from keybert import KeyBERT
from sentence_transformers import util
from hdbscan import HDBSCAN
from collections import defaultdict
import umap.umap_ as umap
import plotly.express as px
import pandas as pd
import networkx as nx
import numpy as np
from langchain_text_splitters import RecursiveCharacterTextSplitter
import torch
from jinja2 import Environment, FileSystemLoader
import tempfile
import os
from litellm import embedding
from keybert.backend import BaseEmbedder
from langchain_openai import AzureChatOpenAI

NAMING_PROMPT = (
    'Suggest one scientific, technical keyword that best describes the context. '
    'Avoid all formatting and output strictly in plaintext and lowercase.'
    '\n\nContext: {context}'
    '\n\nSuggested one keyword: '
)

class StatelessEmbedder(BaseEmbedder):
    def __init__(self, model_name, inference_mode):
        super().__init__()
        self.model_name = model_name
        self.inference_mode = inference_mode

    def embed(self, documents):
        """
        Generate embeddings from either Ollama, HuggingFace
        or Azure OpenAI as a numpy array.
        """
        match self.inference_mode:
            case 'ollama':
                # Convert to JSON-serializable list — numpy arrays cannot be serialized!
                documents = documents.tolist() if isinstance(documents, np.ndarray) else documents
                response = embedding(
                    model=f'ollama/{self.model_name}',
                    input=documents,
                    api_base='http://localhost:11434'
                )
            case 'huggingface':
                response = embedding(
                    model=f'huggingface/{self.model_name}',
                    input=documents,
                    api_key=os.environ['HF_TOKEN'],
                    api_base=os.environ['HF_ENDPOINT']
                )
            case _:
                response = embedding(
                    model=f'azure/{self.model_name}',
                    input=documents,
                    api_base=os.environ['AZURE_OPENAI_ENDPOINT'],
                    api_version=os.environ['AZURE_OPENAI_API_VERSION'],
                    api_key=os.environ['AZURE_OPENAI_API_KEY']
                )

        embeddings = np.array([x['embedding'] for x in response.data])
        return embeddings
    
class TopicWeaver:
    def __init__(self, model_name, inference_mode, top_n, cluster_min, chunk_size, naming_method):
        # Parameters
        self.top_n = top_n

        # Helper modules
        self.model = StatelessEmbedder(model_name, inference_mode)
        self.keybert = KeyBERT(model=self.model)
        self.naming_model = AzureChatOpenAI(azure_deployment='gpt-4o', temperature=0, api_version='2024-10-21') if naming_method else None

        self.clusterer = HDBSCAN(min_cluster_size=cluster_min, metric='euclidean')
        self.reducer_2d = umap.UMAP(n_components=2, n_neighbors=10, min_dist=0.01, metric='euclidean', random_state=42)
        self.reducer_3d = umap.UMAP(n_components=3, n_neighbors=10, min_dist=0.01, metric='euclidean', random_state=42)
        self.splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(model_name='gpt-4', chunk_size=chunk_size, chunk_overlap=int(chunk_size*0.125))

    def get_keywords(self, doc: str) -> list[str]:
        """
        Splits and embeds doc and returns the top 10
        most semantically relevant keywords
        """
        chunks = self.splitter.split_text(doc)
        doc_embeddings, word_embeddings = self.keybert.extract_embeddings(
            docs=chunks
        )
        result = self.keybert.extract_keywords(
            docs=chunks,
            doc_embeddings=doc_embeddings,
            word_embeddings=word_embeddings,
            top_n=self.top_n, 
            nr_candidates=self.top_n*2
        )
        
        keywords = list(set(self.extract_keybert(result)))  # Reduce to unique keywords
        pooled = np.mean(doc_embeddings, axis=0)            # Pool the meanings of all the chunsk
        
        del doc_embeddings
        del word_embeddings

        kw_similarities = {
            kw: (emb, float(util.cos_sim(pooled, emb)))
            for kw, emb in zip(keywords, self.model.embed(keywords))
        }

        kw_similarities = dict(sorted(
            kw_similarities.items(), 
            key=lambda item: item[-1][-1], 
            reverse=True
        ))

        top_keywords = list(kw_similarities.keys())[:self.top_n]
        
        return top_keywords

    def extract_keybert(self, keybert_results):
        """
        Extracts the keywords from results
        generated by keybert in a recursive manner.
        """
        results = []

        def recurse(item):
            if isinstance(item, tuple):
                results.append(item[0])
            elif isinstance(item, list):
                for subitem in item:
                    recurse(subitem)

        recurse(keybert_results)
        return results

    def cluster_keywords(self, keywords: list[str]) -> dict:
        """
        Clusters keywords into semantic clusters
        and returns a map of their members
        """
        embeddings = self.model.embed(keywords)
        clusters = self.clusterer.fit_predict(embeddings)

        cluster_map = defaultdict(list)
        keyword_embeddings = {}

        for keyword, cluster_id in zip(keywords, clusters):
            if cluster_id != -1: # Skip noise if using HDBSCAN
                cluster_map[int(cluster_id)].append(keyword)
                keyword_embeddings[keyword] = embeddings[keywords.index(keyword)]

        return cluster_map, keyword_embeddings

    def name_cluster(self, keywords: list[str], keyword_embeddings: dict, naming_method: str) -> str:
        """
        Names a cluster of keywords by finding the keyword
        closest to the centroid of the cluster or by generating names via an LLM call.
        """
        def by_centroid():
            embeddings = np.array([keyword_embeddings[kw] for kw in keywords])
            embeddings = torch.from_numpy(embeddings)

            # Calculate centroid and find the keyword closest to it
            centroid = util.normalize_embeddings(embeddings.mean(dim=0, keepdim=True))
            name_index = int(util.cos_sim(centroid, embeddings)[0].argmax())
            name = keywords[name_index]
            return name
        
        def by_generation():
            # Format the keywords into a prompt
            prompt = NAMING_PROMPT.format(context=', '.join(keywords))
            name = self.naming_model.invoke(prompt).content
            return name
        
        try:
            match naming_method:
                case 'centroid': 
                    return by_centroid()
                case 'azure': 
                    return by_generation()
        except:
            return by_centroid()

    def display_2d(self, cluster_map: dict, cluster_names: dict, keyword_embeddings: dict):
        """
        Displays clusters and their member keywords
        """
        flat_keywords, flat_ids = self.flatten_cluster_map(cluster_map)
        flat_names = [cluster_names[cluster_id] for cluster_id in flat_ids]

        embeddings = [keyword_embeddings[kw] for kw in flat_keywords]
        embeddings = self.reducer_2d.fit_transform(embeddings)

        coords = pd.DataFrame({
            'keyword': flat_keywords,
            'x': embeddings[:, 0],
            'y': embeddings[:, 1],
            'cluster': flat_names
        })

        fig = px.scatter(
            coords, 
            x='x', 
            y='y',
            title=f'2D plot of {len(cluster_map)} topics',
            color=flat_names,
            hover_data=['keyword'],
            height=800
        )

        return fig

    def display_3d(self, cluster_map: dict, cluster_names: dict, keyword_embeddings: dict):
        """
        Displays clusters and their member keywords
        """
        flat_keywords, flat_ids = self.flatten_cluster_map(cluster_map)
        flat_names = [cluster_names[cluster_id] for cluster_id in flat_ids]

        embeddings = [keyword_embeddings[kw] for kw in flat_keywords]
        embeddings = self.reducer_3d.fit_transform(embeddings)

        coords = pd.DataFrame({
            'keyword': flat_keywords,
            'x': embeddings[:, 0],
            'y': embeddings[:, 1],
            'z': embeddings[:, 2],
            'cluster': flat_names
        })

        fig = px.scatter_3d(
            coords,
            x='x',
            y='y',
            z='z',
            title=f'3D plot of {len(cluster_map)} topics',
            color='cluster',
            hover_data=['keyword'],
            height=800
        )

        return fig

    def flatten_cluster_map(self, cluster_map: dict) -> tuple:
        """
        Flattens a cluster map and returns two equally long lists
        """
        flat_keywords = [
            kw 
            for group in cluster_map.values() 
            for kw in group
        ]
        flat_ids = [
            mapped_id 
            for cluster_id in cluster_map.keys() 
            for mapped_id in [cluster_id] * len(cluster_map[cluster_id]) 
        ]
        return flat_keywords, flat_ids

    def create_graph(self, cluster_map, cluster_names, titles, docs_keywords):
        """
        Craetes graphs of articles linked via topics
        using topic clusters made up of keywords
        """
        G = nx.Graph()
        kw2cluster = {
            keyword: cluster_id
            for cluster_id, keywords in cluster_map.items()
            for keyword in keywords
        }

        # Add cluster nodes
        for cluster_id, cluster_name in cluster_names.items():
            G.add_node(f'cluster_{cluster_id}',  label=f'{cluster_name} (topic)', type='cluster')
        
        # Add article nodes
        for i, pair in enumerate(zip(titles, docs_keywords)):
            title, keywords = pair[0], pair[1]
            G.add_node(f'article_{i}', label=f'{title} (article)', type='article')

            added_clusters = set()
            
            for kw in keywords:
                if kw in kw2cluster:
                    cluster_id = kw2cluster[kw]
                    # Add edge between cluster and article
                    if cluster_id and cluster_id not in added_clusters:
                        G.add_edge(f'article_{i}', f'cluster_{cluster_id}')

        return G, kw2cluster

    def display_graph(self, G):
        """
        Creates and returns a viewable
        graph as an HTML file.
        """
        nodes = [{"id": n, "label": G.nodes[n]['label'], "type": G.nodes[n]['type']} for n in G.nodes()]
        edges = [{"from": u, "to": v} for u, v in G.edges()]
        graph_data = {'nodes': nodes, 'edges': edges}
        
        env = Environment(loader=FileSystemLoader('./'))
        html_graph = str(env.get_template('/template.jinja').render(data=graph_data))

        # Write it to a temporary file
        temp_dir = tempfile.gettempdir()
        file_path = os.path.join(temp_dir, "topic_graph.html")

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html_graph)

        return file_path
    
    def assign_tags(self, titles, docs_keywords, kw2cluster, cluster_names):
        """
        Creates a dataframe consisting of the articles, their keywords and
        their topics. Useful for informing tag assignment.
        """
        article2topics = [
            list(set(cluster_names[kw2cluster[kw]] for kw in keywords if kw in kw2cluster))
            for keywords in docs_keywords
        ]
        
        # Index agnostic
        tags_df = pd.DataFrame({
            'title': titles,
            'topics': article2topics,
            'keywords': docs_keywords
        })

        # Write the tags to a temporary file
        temp_dir = tempfile.gettempdir()
        file_path = os.path.join(temp_dir, 'topic_tags.csv')

        tags_df.to_csv(file_path, index=False)

        return tags_df, file_path

if __name__ == '__main__':
    # Run the script
    None
